---

- name: Install Nginx
  apt:
     name: nginx
     update_cache: yes
     state: installed

- name: Create the Nginx configuration file
  template:
    src: templates/nginx.j2
    dest: "/etc/nginx/conf.d/{{ project_name }}.conf"
  notify: restart nginx

- name: Disable default nginx site
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent

- name: Make sure nginx service is started
  service:
    name: nginx
    state: started
    enabled: yes

