---

- name: Create the supervisor config file
  template:
    src: templates/supervisor_config.j2
    dest: "/etc/supervisor/conf.d/{{ project_name }}.conf"
    backup: no
  notify: update supervisor

- name: Ensure that the application file permissions are set properly
  file:
    path: "{{ project_path }}"
    recurse: yes
    owner: "{{ gunicorn_user }}"
    group: "{{ gunicorn_group }}"
    state: directory

- name: Restart supervisor
  supervisorctl:
    name: "{{ project_name }}"
    state: restarted