- name: Install MySQL Packages
  apt:
    name: "{{item}}"
    update_cache: yes
    state: present
  with_items:
    - libmysqlclient-dev
    - python-mysqldb
    - mysql-server
    - mysql-client
  tags: packages

- name: Ensure the MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes
  tags: db

- name: Ensure database is created
  mysql_db:
    name: "{{ db_name }}"
    state: present
    encoding: utf8
  tags: db

- name: Ensure user has access to the database
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '{{ db_name }}.*:ALL'
    state: present
  tags: db
